version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
          filters:
            branches:
              only:
                - develop
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME
          filters:
            branches:
              only:
                - release-0.1.2
